apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: default
  namespace: kpack
spec:
  serviceAccountName: kpack-sa
  tag: gcr.io/poddle-mvp/kpack
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/nodejs
