apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: kpack-build
  annotations:
    kpack.io/docker: https://index.docker.io
type: kubernetes.io/basic-auth
stringData:
  username: YOUR_DOCKERHUB_USERNAME
  password: YOUR_DOCKERHUB_TOKEN
